import type { Metadata } from "next";
import './globals.css'
import localFont from 'next/font/local'
import Script from "next/script";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const blackout = localFont({
  src: [
    {
      path: '../../public/fonts/Blackout Sunrise.ttf',
    },
  ],
  variable: '--font-blackout',
  display: 'swap',
});

const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat.ttf',
    },
  ],
  variable: '--font-montserrat',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js?56" strategy="beforeInteractive"/>
      </head>
      <body className={`${blackout.variable} font-sans`}>{children}</body>
    </html>
  );
}
