import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const blackout = localFont({
  src: [
    {
      path: '../../public/fonts/Blackout Sunrise.ttf',
    },
  ],
  variable: '--font-blackout',
  display: 'swap',
});

const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat.ttf',
    },
  ],
  variable: '--font-montserrat',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${blackout.variable} ${montserrat.variable} font-sans`}>{children}</body>
    </html>
  );
}
